### PR TITLE
grammar corrections

### PR DESCRIPTION
**Pull request by squarism**
Hi, I found your blog post while looking for vim and chrome extension tips.
I'm a software developer and I see my coworkers doing cool things with the plugin.
I've also studied a few languages so I know how hard learning a language is.
So please don't take my corrections badly.  :)

English is very confusing.  As I've studied other languages, I've realized how bad it
is.  I'm sorry.  Sorry can mean "my fault, I created English" but in this case I mean
"I feel for you" because I didn't create English.  :)

If you want to ask a question about these, please do.

再见!

### CODE REVIEW

**Comment by brookhong** [comment]
How badly I can take? Distinguish the Language from the planet. :)

Seriously. It's awesome, thank you so much.

What do you mean by `I feel for you`? I see nothing sorry here. Actually, I'm very happy that my English posts got readers, and they understood, even willing to help on grammar corrections.
English is good, at least for me it's better than Chinese in IT world. But it does take much of my time to fill the language gap.

Feel free to post more pull request of corrections on my English posts, including the README doc [here](https://github.com/brookhong/Surfingkeys).

BTW, what kind of cool things(can I use `coolness` here?) your coworkers do?

**Comment by dozer47528** [comment]
v2ex 观光团

这老外真可爱～

**Comment by iyee** [comment]
补一个233

**Comment by HouCoder** [comment]
@squarism Thanks for your work ;-).

**Comment by orvice** [comment]
v2ex观光团。

**Comment by v-sky** [comment]
v2ex观光团

**Comment by MuJJus** [comment]
Like you guy!

**Comment by supgeek-rod** [comment]
v2ex观光团

**Comment by shuangJQ** [comment]
v2ex观光团

**Comment by littlewey** [comment]
v2ex观光团

**Comment by Jonwing** [comment]
v2ex观光团

**Comment by sunjiayao** [comment]
v2ex观光团:)

**Comment by ztmark** [comment]
v2ex观光团:)

**Comment by szpnygo** [comment]
v2ex观光团:)

**Comment by Sevncz** [comment]
v2ex观光团

**Comment by zmj1316** [comment]
v2ex观光团

**Comment by chaoxn** [comment]
v2ex观光团

**Comment by hustlzp** [comment]
V观

**Comment by lukertty** [comment]
v 观

**Comment by timwangdev** [comment]
V

**Comment by vaucn** [comment]
阅

**Comment by skylerzhang** [comment]
v观

**Comment by MiracleWong** [comment]
v2ex观光团

**Comment by kasonpasser** [comment]
v2ex观光团

**Comment by ipeony** [comment]
v2ex观光团

**Comment by 0i** [comment]
v2ex观光团

**Comment by lusfold** [comment]
v2ex观光团

**Comment by sykiewang** [comment]
v2ex观光团

**Comment by Frank-Zhu** [comment]
v2ex观光团

**Comment by kaiiak** [comment]
v2ex观光团

**Comment by nccer** [comment]
v2ex观光团

**Comment by est** [comment]
v2ex观光团。

**Comment by xifangczy** [comment]
v2ex观光团

**Comment by LevyLizzz** [comment]
v观团

**Comment by blueandhack** [comment]
V2EX观光团

**Comment by GavinFoo** [comment]
V2EX观光团

**Comment by fantianwen** [comment]
v2exb观光团

**Comment by lyz1990** [comment]
V2EX观光团

**Comment by jingxiang** [comment]
V2EX观光团

**Comment by moonou** [comment]
v2观

**Comment by mgcnrx11** [comment]
v2ex观光团

**Comment by yechengxiao** [comment]
v2ex观光团

**Comment by DIYgod** [comment]
团光观xe2v

**Comment by GerrieWell** [comment]
v2ex留名

**Comment by imcaffrey** [comment]
v2ex观光团

**Comment by bryantchan** [comment]
v2ex观光团

**Comment by squarism** [comment]
> How badly I can take? Distinguish the Language from the planet. :)
"How badly can I take it?"

> What do you mean by I feel for you?
Hard to explain but I feel a certain responsibility for English being confusing.  I know that this is a silly thought.  English is a mutt, a combination of languages and it makes no sense.  Human languages are not computer languages but I think English is bad in a lot of ways because it was never "designed". :expressionless: 

> But it does take much of my time to fill the language gap.
It's a major barrier.  I think Chinese is super interesting (I only know a few characters and I can't quite hear all the tones), I haven't really tried to learn it.  I want to study chinese history, particularly around the 1980s first so I have more context.  :smile: 

> BTW, what kind of cool things(can I use coolness here?) your coworkers do?
"What kind of cool things do your coworkers do" (this is confusing with the extra do).
Cool things is correct.  I see them using cool vim plugins.  Observing is a great way to learn!  :tada:

**Comment by squarism** [comment]
I'll also say that when I was editing your writing (which isn't bad by the way!  don't be sad!) ... it was very similar to editing English grammar.  It's just _rewording_.  So, even for english speakers, there is sometimes a better way to say something (like in code).  :smile:

**Pull request merged**
